/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[22],{473:function(Aa,xa,r){function oa(db){return Object(Ha.b)(void 0,void 0,void 0,function(){var cb,wa,Ka,Ta,Za,hb,kb,bb,pb,ub,tb,Ab,lb,vb,Db;return Object(Ha.d)(this,function(Fb){switch(Fb.label){case 0:return cb=db.lb,wa=db.Tm,Ka=db.Um,Ta=db.Pq,Za=db.ZL,hb=db.PL,kb=gb.getDocument(),bb=[1],[4,Object(za.c)(wa,{extension:"pdf"})];case 1:return pb=Fb.ca(),ub=gb.ka(),lb=(Ab=Ra.a).KZ,[4,pb.bx()];case 2:return tb=lb.apply(Ab,[Fb.ca().xfdfString,
cb]),vb=!0,[4,kb.xf(pb,bb,cb,vb)];case 3:return Fb.ca(),[4,kb.$f([cb+1],vb)];case 4:return Fb.ca(),Db=ub.Xa().filter(function(Qb){return Qb.mE()&&Qb.PageNumber===cb}),ub.oe(Db,{force:!0,source:"contentEditTool"}),[4,ub.aE(tb)];case 5:return Fb.ca(),Ia||(gb.getDocument().vF(),gb.sF(cb),gb.Sd()),aa(cb),hb||Za||pa(cb,Ka,Ta,Za),[2]}})})}function na(db){if(db)return ma(db.contents);Object(Ea.g)("Unable to extract document content")}function ma(db){db=(new DOMParser).parseFromString(db,"text/html").documentElement.querySelector("body");
db.querySelectorAll("p").forEach(function(cb){cb.querySelectorAll("span").forEach(function(Ta){var Za=Ta.getAttribute("style");Za=fa(Za,Ta.innerHTML);Ta.innerHTML=Za});var wa=cb.getAttribute("style"),Ka=cb.innerHTML.replaceAll("<br>","");cb.innerHTML=fa(wa,Ka)});return db.innerHTML.trim()}function fa(db,cb){if(null===db||void 0===db?0:db.includes("bold"))cb="<strong>"+cb+"</strong>";if(null===db||void 0===db?0:db.includes("italic"))cb="<em>"+cb+"</em>";if((null===db||void 0===db?0:db.includes("underline:1;"))||
(null===db||void 0===db?0:db.includes("text-decoration: underline")))cb="<u>"+cb+"</u>";return cb}function da(db){if(["STRONG","EM","U"].includes(db.tagName)&&null!==db.getAttribute("style")){var cb=document.createElement("span"),wa=db.style.color;wa=ca(wa);cb.setAttribute("style","color:"+wa);db.removeAttribute("style");cb.innerHTML=db.innerHTML;db.innerHTML="";db.appendChild(cb)}else"SPAN"===db.tagName&&null!==db.getAttribute("style")?(wa=db.style.color,wa=ca(wa),db.setAttribute("style","color:"+
wa)):"A"===db.tagName&&db.removeAttribute("style")}function aa(db){var cb=gb.ka(),wa=cb.Xa().filter(function(Ka){return Ka.ie()&&Ka.PageNumber===db});cb.oe(wa,{force:!0,source:"contentEditTool"})}function y(db,cb){cb.forEach(function(wa){Va[db]||(Va[db]=[]);Va[db].find(function(Ka){return Ka.id===wa.id})||Va[db].push(wa)})}function w(db,cb){cb.forEach(function(wa){Pa[db]||(Pa[db]=[]);Pa[db].find(function(Ka){return Ka.id===wa.id})||Pa[db].push(wa)})}function f(db,cb,wa,Ka){return Object(Ha.b)(void 0,
void 0,void 0,function(){var Ta,Za,hb,kb,bb,pb,ub,tb,Ab,lb,vb,Db,Fb,Qb,Pb,Tb,ya,Zb;return Object(Ha.d)(this,function(gc){switch(gc.label){case 0:if(!db)return[2];Ta=cb.replaceAll("<p><br></p>","");Za=a(Ta);Za=Za.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");Za=Za.replace(/<span class="ql-cursor">(.*?)<\/span>/g,"");hb=db.Tc.id;kb=db.PageNumber;bb=eb[kb];pb=bb.galleys.find(function(Qc){return Qc.id===hb});ub=ma(pb.contents);tb=ia(kb,bb,ub,Za,hb);if(""===tb)return[3,2];Ab=
new TextEncoder;lb=Ab.encode(tb);vb=lb.buffer;Db=Object(La.c)()||"https://www.pdftron.com/webfonts/v2/";Fb=gb.getDocument();return[4,Fb.Kc([kb],void 0,!0)];case 1:return Qb=gc.ca(),Ab=new TextEncoder,Pb=Ab.encode(""),Tb=Pb.buffer,ob.postMessage({cmd:"importText",pdfFile:Qb,pageNumber:kb,webFontURL:Db,galleyId:hb,importData:vb,tableData:Tb,isSearchReplace:wa,callbackMapId:Ka},[vb,Tb]),ya={},pb&&(Zb=pb.galleyBox,ya={top:Zb.top,left:Zb.left,bottom:Zb.bottom,right:Zb.right}),Object(Sa.w)(ub,Za,ya),[3,
3];case 2:Object(Ea.g)("Unable to generate import XML"),gc.label=3;case 3:return[2]}})})}function a(db){var cb=new DOMParser,wa=cb.parseFromString(db,"text/xml");wa.querySelector("parsererror")&&(wa=cb.parseFromString("<Root>"+db+"</Root>","text/xml"));wa.querySelectorAll("a").forEach(function(Ka){var Ta=Ka.childNodes[0];Array.from(Ka.querySelectorAll("*")).find(function(Za){return"u"===Za.tagName.toLowerCase()})||(Ka=document.createElement("u"),Ta.after(Ka),Ka.appendChild(Ta))});return(new XMLSerializer).serializeToString(wa)}
function b(db,cb,wa){return Object(Ha.b)(void 0,void 0,void 0,function(){var Ka,Ta,Za,hb;return Object(Ha.d)(this,function(kb){switch(kb.label){case 0:return aa(cb),Pa[cb]=[],Va[cb]=[],[4,db.Kc([cb],void 0,!0)];case 1:return Ka=kb.ca(),Ta=new TextEncoder,Za=Ta.encode(""),hb=Za.buffer,ob.postMessage({cmd:"exportFile",pageNumber:cb,performExport:wa,pdfFile:Ka,tableData:hb},[Ka,hb]),[2]}})})}function e(db){return Object(Ha.b)(void 0,void 0,void 0,function(){return Object(Ha.d)(this,function(){mb||(gb=
db,mb=new Promise(function(cb,wa){var Ka=window.Core.ContentEdit.getWorkerPath(),Ta=window.Core.ContentEdit.getResourcePath();ob=new Worker(Ka+"InfixServerModule.js");ob.onmessage=function(Za){ja(Za,cb,wa)};ob.postMessage({cmd:"isReady",resourcePath:Ta})}));return[2,mb]})})}function h(db,cb,wa,Ka){this.top=db;this.left=cb;this.bottom=wa;this.right=Ka;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};
this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};this.width=function(){return Math.round(this.right-this.left)};this.qw=function(Ta){return this.topVal()!==Ta.topVal()||this.leftVal()!==Ta.leftVal()||this.bottomVal()!==Ta.bottomVal()||this.rightVal()!==Ta.rightVal()}}function n(db,cb,wa,Ka,Ta){this.id=db;this.pagenum=cb;this.galleysContents=wa;this.contents=Ka;this.galleyBox=Ta;Object(Sa.v)(Pa)}function z(db,cb,wa,Ka){this.id=
cb;this.type=db;this.bbox=wa;this.pagenum=Ka}function x(db,cb,wa,Ka,Ta){this.id=db;this.pagecount=cb;this.pageBBox=wa;this.galleys=Ka;this.objects=Ta}function ba(db,cb){this.family=db;this.variations=cb}function ia(db,cb,wa,Ka,Ta){var Za=[],hb=[];(new DOMParser).parseFromString(Ka,"text/html").documentElement.querySelectorAll("p").forEach(function(tb,Ab){Za[Ab]=tb.innerHTML;hb[Ab]={fontSize:tb.style.fontSize,fontFamily:tb.style.fontFamily,color:ca(tb.style.color)}});wa=(new DOMParser).parseFromString(wa,
"text/html");var kb=null;wa.documentElement.querySelectorAll("p").forEach(function(tb,Ab){if(Ab<Za.length){var lb=(new DOMParser).parseFromString(Za[Ab],"text/html").documentElement.querySelector("body");lb.childNodes.forEach(function(Db){da(Db)});tb.innerHTML=lb.innerHTML;kb=tb.getAttribute("style");lb=hb[Ab].fontSize?hb[Ab].fontSize:tb.style.fontSize;var vb=hb[Ab].fontFamily?hb[Ab].fontFamily.replace(/\s+/g,"").replace(/['"]+/g,""):tb.style.fontFamily;Ab=hb[Ab].color?hb[Ab].color:null;kb=kb.replace(/(font:.*?;)/i,
"font:normal normal "+lb+" "+vb+";");kb=kb.replace("Italic","");kb=kb.replace("underline:1;","underline:0;");kb=kb.replace("text-decoration: underline;","text-decoration: none;");Ab&&(kb=kb.replace(/(color:.*?;)/i,"color:"+Ab+";"));tb.setAttribute("style",kb)}else tb.remove()});for(Ka=wa.documentElement.querySelectorAll("p").length;Ka<Za.length;Ka++){var bb=document.createElement("p");bb.setAttribute("id","0");var pb=(new DOMParser).parseFromString(Za[Ka],"text/html").documentElement.querySelector("body");
pb.childNodes.forEach(function(tb){da(tb)});bb.innerHTML=pb.innerHTML;null!=kb&&bb.setAttribute("style",kb);wa.documentElement.querySelector("body").appendChild(bb)}wa=wa.documentElement.querySelector("body").innerHTML;var ub="";Pa[db].forEach(function(tb){tb.id===Ta&&(ub=tb)});if(""===ub)return"";cb="<DOC id='"+cb.id+"' pagecount='"+cb.pagecount+"'>";cb=cb+("<STORY galley_ids='"+Ta+"' pagenum='"+db+"'><galleys>")+(ub.galleysContents+"</galleys>");ub.contents=wa;cb=cb+wa+"\n</STORY>";return cb+="</DOC>"}
function ca(db){return db.startsWith("rgb(")?"#"+db.replace(/^[^\d]+/,"").replace(/[^\d]+$/,"").split(",").map(function(cb){return("00"+parseInt(cb,10).toString(16)).slice(-2)}).join(""):db}function ea(db,cb,wa,Ka){var Ta=[],Za=gb.getDocument(),hb=null;cb.forEach(function(kb){if(kb instanceof z){var bb=Za.Zh(db,kb.bbox.leftVal(),kb.bbox.topVal());var pb=bb.x;var ub=bb.y;var tb=Za.Zh(db,kb.bbox.rightVal(),kb.bbox.bottomVal());bb=tb.x;tb=tb.y}else if(kb instanceof n)bb=Za.Zh(db,kb.galleyBox.leftVal(),
kb.galleyBox.topVal()),pb=bb.x,ub=bb.y,tb=Za.Zh(db,kb.galleyBox.rightVal(),kb.galleyBox.bottomVal()),bb=tb.x,tb=tb.y;else return;var Ab=new window.Core.Annotations.RectangleAnnotation,lb=Fa.a.OBJECT;kb instanceof n&&(lb=Fa.a.TEXT);Ab.r0(kb,lb);Ab.PageNumber=kb.pagenum;Ab.X=pb;Ab.Y=ub;Ab.Width=bb-pb;Ab.Height=tb-ub;Ab.StrokeColor=new Ja.a("#3183C8");Ab.FillColor=new Ja.a(255,255,255,.01);Ab.Style="dash";Ab.Dashes="4,3";if(Ya||Ka)Ab.NoView=!0,Ab.Listable=!1;Ab.Ts();Ab.selectionModel=Oa.a;Ta.push(Ab);
"undefined"!==typeof wa&&wa===kb.id&&(hb=Ab)});cb=gb.ka();cb.pg(Ta);!hb||Ya||Ka||cb.Df(hb);cb.ee(Ta)}function ja(db,cb,wa){return Object(Ha.b)(this,void 0,void 0,function(){var Ka,Ta,Za,hb,kb,bb,pb,ub,tb,Ab;return Object(Ha.d)(this,function(lb){switch(lb.label){case 0:Ka=db.data;console.log("MESSAGE FROM INFIX SERVER WORKER: ",Ka);Za=Ka.cmd;switch(Za){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "loadAvailableFonts":return[3,4];case "exportFile":return[3,5];case "insertNewTextBox":return[3,
6];case "importText":return[3,7];case "transformObject":return[3,7];case "alignParagraph":return[3,7];case "deleteObject":return[3,8];case "insertImage":return[3,9]}return[3,10];case 1:return[4,Object(Qa.b)()];case 2:return hb=lb.ca(),ob.postMessage({cmd:"initialiseInfixServer",l:hb}),[3,10];case 3:return(kb=ka(Ka.resultsXML))?(cb(),bb=Object(La.c)()||"https://www.pdftron.com/webfonts/v2/",ob.postMessage({cmd:"loadAvailableFonts",webFontURL:bb})):wa("License key does not have content edit permission"),
[3,10];case 4:return Ca(Ka.resultsXML),[3,10];case 5:return Ka.exportPerformed?qa(Ka.pageNumber,Ka.exportXML,Ka.objectXML,Ka.resultsXML):(Ta=eb[Ka.pageNumber],la(Ka.pageNumber,Ta)),rb.resolve(),zb&&zb[Ka.pageNumber]&&zb[Ka.pageNumber].resolve(),[3,10];case 6:return ha(Ka.pageNumber,Ka.exportXML,Ka.contentHTML),Ta=eb[Ka.pageNumber],oa({lb:Ka.pageNumber,Tm:Ka.pdfBuffer,Um:Ta,Pq:Ka.id}),[3,10];case 7:Ta=eb[Ka.pageNumber];Da(Ka.pageNumber,Ka.resultsXML);oa({lb:Ka.pageNumber,Tm:Ka.pdfBuffer,Um:Ta,Pq:Ka.id,
ZL:Ka.isSearchReplace});pb=Ka.isSearchReplace;ub=Ka.callbackMapId;if(pb&&ub&&Nb[ub])Nb[ub]();return[3,10];case 8:return Ta=eb[Ka.pageNumber],Da(Ka.pageNumber,Ka.resultsXML),Ta.galleys=Ta.galleys.filter(function(vb){return vb.id!==Ka.id}),Ta.objects=Ta.objects.filter(function(vb){return vb.id!==Ka.id}),tb={lb:Ka.pageNumber,Tm:Ka.pdfBuffer,Um:Ta},oa(tb),[3,10];case 9:return Ta=eb[Ka.pageNumber],Da(Ka.pageNumber,Ka.resultsXML),Ab={lb:Ka.pageNumber,Tm:Ka.pdfBuffer,Um:Ta,Pq:Ka.isText,PL:!0},oa(Ab),[3,
10];case 10:return[2]}})})}function ka(db){db=new Uint8Array(db);var cb=(new TextDecoder("utf-8")).decode(db);db=!1;cb=(new DOMParser).parseFromString(cb,"text/xml").getElementsByTagName("LicenseCheck");null!==cb&&0<cb.length&&(cb=cb[0].getElementsByTagName("Status")[0].innerHTML,"error"!==cb&&"ok"===cb&&(db=!0));return db}function ha(db,cb){cb=(new TextDecoder("utf-8")).decode(cb);cb=(new DOMParser).parseFromString(cb,"text/xml").getElementsByTagName("STORY");var wa=Array.prototype.slice.call(cb)[0];
cb=wa.getAttribute("galley_ids");var Ka=Array.prototype.slice.call(wa.getElementsByTagName("g"))[0],Ta=Ka.getAttribute("bbox").split(" ");Ta=new h(parseFloat(Ta[0]),parseFloat(Ta[1]),parseFloat(Ta[2]),parseFloat(Ta[3]));Ka=Ka.innerHTML;var Za=Array.prototype.slice.call(wa.getElementsByTagName("galleys"))[0];Za.parentNode.removeChild(Za);wa=va(wa.innerHTML).trim();cb=new n(cb,db,Ka,wa,Ta);wa=eb[db];Ta=wa.galleys;Ta.push(cb);wa.galleys=Ta;eb[db]=wa;la(db,wa)}function la(db,cb){w(db,cb.galleys);y(db,
cb.objects);aa(db);pa(db,cb)}function pa(db,cb,wa,Ka){ea(db,cb.objects,wa,Ka);ea(db,cb.galleys,wa,Ka)}function qa(db,cb,wa,Ka){var Ta=new Uint8Array(cb),Za=new TextDecoder("utf-8");cb=Za.decode(Ta);Ta=new Uint8Array(wa);wa=Za.decode(Ta);Ta=new Uint8Array(Ka);Ka=Za.decode(Ta);eb[db]=ua(db,cb,wa,Ka);la(db,eb[db])}function ra(db,cb){db=parseFloat(db);return isNaN(cb)||cb<db?db:cb}function ua(db,cb,wa,Ka){var Ta;var Za=new DOMParser;Ka=Za.parseFromString(Ka,"text/xml");Array.prototype.slice.call(Ka.getElementsByTagName("BBox")).forEach(function(bb){if("CropBox"===
bb.getAttribute("Name")){var pb=parseFloat(bb.getElementsByTagName("Top").item(0).innerHTML),ub=parseFloat(bb.getElementsByTagName("Bottom").item(0).innerHTML),tb=parseFloat(bb.getElementsByTagName("Left").item(0).innerHTML);bb=parseFloat(bb.getElementsByTagName("Right").item(0).innerHTML);Ta=new h(pb,tb,ub,bb)}});Za=new DOMParser;Ka=Za.parseFromString(cb,"text/xml");var hb=[];Array.prototype.slice.call(Ka.getElementsByTagName("STORY")).forEach(function(bb){var pb=bb.getAttribute("galley_ids"),ub=
Array.prototype.slice.call(bb.getElementsByTagName("g"))[0],tb=ub.getAttribute("bbox").split(" ");tb=new h(parseFloat(tb[0]),parseFloat(tb[1]),parseFloat(tb[2]),parseFloat(tb[3]));ub=ub.innerHTML;var Ab=Array.prototype.slice.call(bb.getElementsByTagName("galleys"))[0];Ab.parentNode.removeChild(Ab);bb=va(bb.innerHTML).trim();pb=new n(pb,db,ub,bb,tb);hb.push(pb)});Za=new DOMParser;var kb=[];cb=Za.parseFromString(wa,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(cb).forEach(function(bb){var pb=
bb.getAttribute("Type"),ub=bb.getAttribute("OID");bb=Array.prototype.slice.call(bb.getElementsByTagName("Point"));var tb=Number.NaN,Ab=Number.NaN,lb=Number.NaN,vb=Number.NaN;bb.forEach(function(Db){var Fb=Db.getAttribute("Name");"TL"===Fb?(tb=ra(Db.getAttribute("Y"),tb),lb=ra(Db.getAttribute("X"),lb)):"TR"===Fb?(tb=ra(Db.getAttribute("Y"),tb),vb=ra(Db.getAttribute("X"),vb)):"BR"===Fb?(Ab=ra(Db.getAttribute("Y"),Ab),vb=ra(Db.getAttribute("X"),vb)):"BL"===Fb&&(Ab=ra(Db.getAttribute("Y"),Ab),lb=ra(Db.getAttribute("X"),
lb))});bb=new h(tb,lb,Ab,vb);pb=new z(pb,ub,bb,db);kb.push(pb)});cb=Array.prototype.slice.call(Ka.getElementsByTagName("DOC"))[0].getAttribute("id");return new x(cb,1,Ta,hb,kb)}function va(db){return(new DOMParser).parseFromString(db,"text/html").documentElement.querySelector("body").innerHTML}function Da(db,cb){var wa;cb=(new TextDecoder("utf-8")).decode(cb);var Ka=(new DOMParser).parseFromString(cb,"text/xml");cb=Ka.getElementsByTagName("Galley").item(0);if(null!=cb){var Ta=cb.getAttribute("id");
cb=Ka.getElementsByTagName("BBox");cb=Array.prototype.slice.call(cb);cb.forEach(function(kb){var bb=kb.getElementsByTagName("Top"),pb=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Left");var ub=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Bottom");var tb=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Right");kb=parseFloat(bb.item(0).innerHTML);wa=new h(pb,ub,tb,kb)});Pa[db].forEach(function(kb){kb.id===Ta&&!0===wa.qw(kb.galleyBox)&&(kb.galleyBox=wa)})}cb=
Ka.getElementsByTagName("Object").item(0);if(null!=cb){var Za=cb.getAttribute("OID");cb=Ka.getElementsByTagName("BBox");cb=Array.prototype.slice.call(cb);cb.forEach(function(kb){var bb=kb.getElementsByTagName("Top"),pb=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Left");var ub=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Bottom");var tb=parseFloat(bb.item(0).innerHTML);bb=kb.getElementsByTagName("Right");kb=parseFloat(bb.item(0).innerHTML);wa=new h(pb,ub,tb,kb)});Va[db].forEach(function(kb){kb.id===
Za&&!0===wa.qw(kb.bbox)&&(kb.bbox=wa)})}cb=Ka.getElementsByTagName("NewParas").item(0);if(null!=cb){var hb=cb.getAttribute("id");Pa[db].forEach(function(kb){if(kb.id===hb){var bb="<Contents>"+kb.contents;bb+="</Contents>";var pb=Array.prototype.slice.call(Ka.getElementsByTagName("NewPara"));bb=(new DOMParser).parseFromString(bb,"text/xml");var ub=Array.prototype.slice.call(bb.getElementsByTagName("p"));pb.forEach(function(tb){var Ab=parseFloat(tb.innerHTML),lb=!1;ub.forEach(function(vb){var Db=vb.getAttribute("id");
!1===lb&&"0"===Db&&(vb.setAttribute("id",Ab),lb=!0)})});kb.contents=bb.getElementsByTagName("Contents").item(0).innerHTML}})}}function sa(db){return{regex:0!==(db&fb.f.Sr),wildcard:0!==(db&fb.f.sp),wholeWord:0!==(db&fb.f.Vr),caseSensitive:0!==(db&fb.f.np)}}function Ca(db){db=new Uint8Array(db);db=(new TextDecoder("utf-8")).decode(db);db=(new DOMParser).parseFromString(db,"text/xml").getElementsByTagName("Font");var cb={};Array.prototype.slice.call(db).forEach(function(wa){var Ka=wa.getAttribute("Family");
Ka in cb||(cb[Ka]={});var Ta=[];Array.prototype.slice.call(wa.getElementsByTagName("Variation")).forEach(function(Za){Za=Za.innerHTML;Ta.push(Za);if(Za.includes("Regular")||Za===Ka.replace(/\s+/g,""))cb[Ka].hasRegular=!0;Za.includes("Bold")&&(cb[Ka].hasBold=!0);Za.includes("Italic")&&(cb[Ka].hasItalic=!0)});wa=new ba(Ka,Ta);Bb.push(wa)});Jb=Object.keys(cb).filter(function(wa){return cb[wa].hasRegular&&cb[wa].hasBold&&cb[wa].hasItalic})}r.r(xa);var Ha=r(0),za=r(52),Ja=r(7),Oa=r(485),La=r(39),Qa=r(76),
Ea=r(2),Fa=r(166),Sa=r(55),Ra=r(6),Xa=r(137),fb=r(25),Wa=r(8),sb=r(23),ob=null,mb=null,Ya=!1,Ia=!1,Pa={},Va={},eb={},gb,rb=window.createPromiseCapability(),zb=[],Bb=[],Jb=[],Nb={};xa["default"]={IZ:e,JZ:b,tU:function(db){return Object(Ha.b)(void 0,void 0,void 0,function(){var cb,wa,Ka,Ta,Za,hb,kb,bb;return Object(Ha.d)(this,function(pb){switch(pb.label){case 0:return cb=db.id,wa=db.isText,Ka=db.pageNumber,Ta=gb.getDocument(),[4,Ta.Kc([Ka],void 0,!0)];case 1:return Za=pb.ca(),hb=new TextEncoder,kb=
hb.encode(""),bb=kb.buffer,ob.postMessage({cmd:"deleteObject",pdfFile:Za,pageNumber:Ka,objectID:cb,isText:wa,tableData:bb},[bb]),[2]}})})},X1:function(db){return Object(Ha.b)(void 0,void 0,void 0,function(){var cb,wa,Ka,Ta,Za,hb,kb,bb,pb,ub,tb,Ab,lb;return Object(Ha.d)(this,function(vb){switch(vb.label){case 0:return cb=db.id,wa=db.position,Ka=wa.top,Ta=wa.left,Za=wa.bottom,hb=wa.right,kb=db.isText,bb=db.pageNumber,pb=gb.getDocument(),[4,pb.Kc([bb],void 0,!0)];case 1:return ub=vb.ca(),tb=new TextEncoder,
Ab=tb.encode(""),lb=Ab.buffer,ob.postMessage({cmd:"transformObject",pdfFile:ub,pageNumber:bb,objectID:cb,isText:kb,topVal:Ka,leftVal:Ta,bottomVal:Za,rightVal:hb,tableData:lb},[lb]),[2]}})})},FS:function(db,cb){return Object(Ha.b)(void 0,void 0,void 0,function(){var wa,Ka,Ta,Za,hb,kb,bb,pb,ub,tb,Ab,lb,vb,Db,Fb;return Object(Ha.d)(this,function(Qb){switch(Qb.label){case 0:return wa="<DOC><STORY><galleys></galleys>",Ka=[],Ta=(new DOMParser).parseFromString(cb,"text/html"),Ta.documentElement.querySelectorAll("p").forEach(function(Pb,
Tb){Ka[Tb]=Pb.innerHTML}),Ka.forEach(function(Pb,Tb){Pb=(new DOMParser).parseFromString(Ka[Tb],"text/html").documentElement.querySelector("body");Pb.childNodes.forEach(function(ya){da(ya)});wa+="<p>"+Pb.innerHTML+"</p>"}),wa+="</STORY></DOC>",Za=db.pageNumber,hb=gb.getDocument(),kb=db.position,bb=kb.top,pb=kb.left,ub=kb.bottom,tb=kb.right,Ab=db.defaultText,lb=db.font,vb=db.fontSize,Db=db.textColor,[4,hb.Kc([Za],void 0,!0)];case 1:return Fb=Qb.ca(),ob.postMessage({cmd:"insertNewTextBox",pdfFile:Fb,
pageNumber:Za,topVal:bb,leftVal:pb,bottomVal:ub,rightVal:tb,defaultText:Ab,font:lb,fontSize:vb,textColor:Db,importData:wa,content:cb}),[2]}})})},g2:f,SV:na,b0:function(db){return Object(Ha.b)(this,void 0,void 0,function(){var cb,wa,Ka,Ta,Za,hb,kb,bb,pb,ub,tb,Ab,lb,vb,Db,Fb,Qb,Pb,Tb,ya,Zb,gc,Qc=this;return Object(Ha.d)(this,function(Kc){switch(Kc.label){case 0:cb=db.replaceWith;wa=db.documentViewer;Ka=db.search;Ta=db.searchResults;if(wa){if(!Ta&&!Ka)throw Error('The "searchResults" parameter is missing in the options');
if(void 0===cb)throw Error('The "replaceWith" parameter should not be undefined');}else throw Error('The "documentViewer" parameter is missing in the options');Za=1===Ta.length;Ka?(hb=Ka.$I,kb=Ka.bP):(bb=sa(wa.qx()),hb=bb.$I,kb=bb.bP);pb=null;ub=[];if(Za)pb=Ta[0],ub=[pb.pageNum];else try{ub=Object.keys(Ta.reduce(function(ec,zc){ec[zc.pageNum]=zc.pageNum;return ec},{})).map(function(ec){return Number(ec)})}catch(ec){Object(Ea.i)(ec)}tb=0;if(pb)for(Ab=wa.Wi(),lb=-1,vb=0,Db=Ab.length;vb<Db&&(Fb=Ab[vb],
Fb.pageNum===lb?tb++:(lb=Fb.pageNum,tb=0),!Object(Xa.a)(Fb,pb));vb++);Qb=Ta[0].resultStr;Pb=hb?"mg":"mgi";Tb=kb?"\\b("+Qb+")\\b":"("+Qb+")";ya=new RegExp("(?<!</?[^>]*|&[^;]*)"+Tb,Pb);rb=window.createPromiseCapability();return mb?[3,2]:[4,e(wa)];case 1:Kc.ca(),Kc.label=2;case 2:return Ya=!0,Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_STARTED),Zb=0,gc=ub.map(function(ec){return Object(Ha.b)(Qc,void 0,void 0,function(){var zc,wc=this;return Object(Ha.d)(this,function(){zc=new Promise(function(Lc,Sd){return Object(Ha.b)(wc,
void 0,void 0,function(){var nc=this;return Object(Ha.d)(this,function(kc){switch(kc.label){case 0:return zb[ec]=window.createPromiseCapability(),[4,b(wa.getDocument(),ec,!0)];case 1:return kc.ca(),zb[ec].promise.then(function(){return Object(Ha.b)(nc,void 0,void 0,function(){function Rd(Hc,ad){return Object(Ha.b)(this,void 0,void 0,function(){var Mc,rd;return Object(Ha.d)(this,function(Cb){switch(Cb.label){case 0:Mc=Object(sb.f)(),Nb[Mc]=function(){delete Nb[Mc];Lc(!0);Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_TEXT_REPLACED)},
Cb.label=1;case 1:return Cb.Ff.push([1,3,,4]),[4,f(Hc,ad,!0,Mc)];case 2:return Cb.ca(),[3,4];case 3:return rd=Cb.ca(),Object(Ea.i)(rd),Sd(rd),[3,4];case 4:return[2]}})})}var Zd,id,td,jd,lc,Md,Rc,Dd,Fc,oc,ud,Td,vd,wd,Nd,Ed,hd;return Object(Ha.d)(this,function(){Zd=gb.ka();id=Zd.Xa().filter(function(Hc){return Hc.PageNumber===ec}).filter(function(Hc){return Hc.ie()}).concat();td=[];lc=jd=0;for(Md=id.length;lc<Md;lc++){Rc=id[lc];Dd=Rc.Tc;Fc=na(Dd);oc=[];try{for(ud=void 0;null!==(ud=ya.exec(Fc));)oc.push(ud),
td.push(Ta[Zb]),Zb++}catch(Hc){Object(Ea.i)(Hc)}if(oc.length)if(jd+=oc.length,Za&&jd>tb){Td=Math.abs(jd-oc.length-tb);vd=oc[Td].index;wd=Fc.substr(0,vd);Nd=cb;Ed=Fc.substr(vd+Qb.length,Fc.length);hd=""+wd+Nd+Ed;Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_TEXT_FOUND,[[pb]]);Rd(Rc,hd);break}else Za||(Ia=!0,hd=Fc.replace(ya,cb),Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_TEXT_FOUND,[td]),Rd(Rc,hd))}return[2]})})}).catch(Sd),[2]}})})});return[2,zc]})})}),[2,Promise.all(gc).then(function(){Za&&pb?setTimeout(function(){var wc=
[];wa.fv(Ta[0].resultStr,wa.qx(),{startPage:ub[0],endPage:ub[0],fullSearch:!0,onDocumentEnd:function(){Ia=Ya=!1;Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_ENDED);wa.uG(ub[0]-1,wc)},onResult:function(Lc){Lc.resultCode===fb.e.rl&&wc.push(Lc)}})},200):(wa.gJ(),wa.Vk(),wa.Sd(),Ia=Ya=!1,Sa.a.trigger(Wa.e.SEARCH_AND_REPLACE_ENDED));var ec=gb.ka(),zc=ec.Xa().filter(function(wc){return wc.ie()});ec.oe(zc,{force:!0,source:"contentEditTool"})})]}})})},s0:function(db,cb){var wa=ma(db.Tc.contents);wa=(new DOMParser).parseFromString(wa,
"text/html").documentElement.querySelector("body");var Ka=wa.querySelectorAll("p"),Ta=new XMLSerializer;Ka.forEach(function(Za){Za.style.fontFamily=cb});wa=Ta.serializeToString(wa);f(db,wa)},t0:function(db,cb){var wa=ma(db.Tc.contents);wa=(new DOMParser).parseFromString(wa,"text/html").documentElement.querySelector("body");var Ka=wa.querySelectorAll("p"),Ta=new XMLSerializer;Ka.forEach(function(Za){Za.style.fontSize=cb});wa=Ta.serializeToString(wa);f(db,wa)},NS:function(db,cb){return Object(Ha.b)(void 0,
void 0,void 0,function(){var wa,Ka,Ta,Za,hb,kb,bb;return Object(Ha.d)(this,function(pb){switch(pb.label){case 0:return wa=db.Tc.id,Ka=db.PageNumber,Ta=gb.getDocument(),[4,Ta.Kc([Ka],void 0,!0)];case 1:return Za=pb.ca(),hb=new TextEncoder,kb=hb.encode(""),bb=kb.buffer,ob.postMessage({cmd:"AlignParaText",pdfFile:Za,pageNumber:Ka,galleyID:wa,alignment:cb,topVal1:"",leftVal1:"",bottomVal1:"",rightVal1:"",topVal2:"",leftVal2:"",bottomVal2:"",rightVal2:"",tableData:bb},[bb]),[2]}})})},nT:function(db){var cb=
ma(db.Tc.contents);cb=(new DOMParser).parseFromString(cb,"text/html").documentElement.querySelector("body");var wa=cb.querySelectorAll("p"),Ka=new XMLSerializer,Ta="bold"===wa[0].style.fontWeight,Za=Ka.serializeToString(wa[0]).includes("<strong>");wa.forEach(function(hb){if(Ta||Za){hb.style.fontWeight="normal";var kb=Ka.serializeToString(hb).replace(/<strong>/g,"");kb=kb.replace(/<\/strong>/g,"");kb=(new DOMParser).parseFromString(kb,"text/html").documentElement.querySelector("p");hb.parentElement.replaceChild(kb,
hb)}else hb.style.fontWeight="bold",hb.innerHTML="<strong>"+hb.innerHTML.trim()+"</strong>"});cb=Ka.serializeToString(cb);f(db,cb)},YX:function(db){var cb=ma(db.Tc.contents);cb=(new DOMParser).parseFromString(cb,"text/html").documentElement.querySelector("body");var wa=cb.querySelectorAll("p"),Ka=new XMLSerializer,Ta="italic"===wa[0].style.fontStyle,Za=Ka.serializeToString(wa[0]).includes("<em>");wa.forEach(function(hb){if(Ta||Za){hb.style.fontStyle="normal";hb.style.font.includes("Italic")&&(hb.style.font=
hb.style.font.replace("Italic",""));var kb=Ka.serializeToString(hb).replace(/<em>/g,"");kb=kb.replace(/<\/em>/g,"");kb=(new DOMParser).parseFromString(kb,"text/html").documentElement.querySelector("p");hb.parentElement.replaceChild(kb,hb)}else hb.style.fontStyle="italic",hb.innerHTML="<em>"+hb.innerHTML.trim()+"</em>"});cb=Ka.serializeToString(cb);f(db,cb)},Z1:function(db){var cb=ma(db.Tc.contents);cb=(new DOMParser).parseFromString(cb,"text/html").documentElement.querySelector("body");var wa=cb.querySelectorAll("p"),
Ka=new XMLSerializer,Ta=wa[0].style.textDecoration.includes("underline")||wa[0].style.textDecoration.includes("word"),Za=Ka.serializeToString(wa[0]).includes("<u>");wa.forEach(function(hb){if(Ta||Za){hb.style.textDecoration=hb.style.textDecoration.replace("underline","");var kb=Ka.serializeToString(hb).replace(/<u>/g,"");kb=kb.replace(/<\/u>/g,"");kb=(new DOMParser).parseFromString(kb,"text/html").documentElement.querySelector("p");hb.parentElement.replaceChild(kb,hb)}else hb.style.textDecoration.includes("none")?
hb.style.textDecoration=hb.style.textDecoration.replace("none","underline"):hb.style.textDecoration+=" underline",hb.innerHTML="<u>"+hb.innerHTML.trim()+"</u>"});cb=Ka.serializeToString(cb);f(db,cb)},R0:function(db,cb){var wa=ma(db.Tc.contents);wa=(new DOMParser).parseFromString(wa,"text/html").documentElement.querySelector("body");var Ka=wa.querySelectorAll("p"),Ta=new XMLSerializer;Ka.forEach(function(Za){Za.style.color=cb});wa.querySelectorAll("span").forEach(function(Za){Za.setAttribute("style",
"color:"+cb)});wa=Ta.serializeToString(wa);f(db,wa)},HV:function(){return Jb},ES:function(db){return Object(Ha.b)(void 0,void 0,void 0,function(){var cb,wa,Ka,Ta,Za,hb,kb,bb,pb,ub;return Object(Ha.d)(this,function(tb){switch(tb.label){case 0:return cb=db.pageNumber,wa=db.newImage,Ka=db.scaleType,Ta=db.position,Za=Ta.top,hb=Ta.left,kb=Ta.bottom,bb=Ta.right,pb=gb.getDocument(),[4,pb.Kc([cb],void 0,!0)];case 1:return ub=tb.ca(),ob.postMessage({cmd:"insertImage",pdfFile:ub,pageNumber:cb,newImage:wa,scaleType:Ka,
topVal:Za,leftVal:hb,bottomVal:kb,rightVal:bb},[]),[2]}})})}}}}]);}).call(this || window)
