/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[5],{471:function(Aa,xa,r){r.r(xa);var oa=r(0),na=r(496),ma=r(497),fa;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(fa||(fa={}));Aa=function(){function da(aa){this.aa=aa;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.wga=function(){var aa=this;return function(y,
w,f){return Object(oa.b)(aa,void 0,void 0,function(){var a,b,e,h,n,z,x,ba=this,ia;return Object(oa.d)(this,function(ca){switch(ca.label){case 0:if(this.state!==fa.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];a=this.aa.getDocument().st();return[4,this.Fea(a)];case 1:b=ca.ca(),e=this.A$(b),this.VJ=null!==(ia=null===e||void 0===e?void 0:e.parse())&&void 0!==ia?ia:null,this.state=null===this.VJ?fa.EXTERNAL_XFDF_NOT_AVAILABLE:fa.EXTERNAL_XFDF_AVAILABLE,ca.label=2;case 2:if(this.state===fa.EXTERNAL_XFDF_NOT_AVAILABLE)return f(y),
[2];h=new DOMParser;n=h.parseFromString(y,"text/xml");w.forEach(function(ea){ba.merge(n,ba.VJ,ea-1)});z=new XMLSerializer;x=z.serializeToString(n);f(x);return[2]}})})}};da.prototype.WN=function(aa){this.Fea=aa};da.prototype.Be=function(){this.VJ=void 0;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.A$=function(aa){return aa?Array.isArray(aa)?new na.a(aa):"string"!==typeof aa?null:(new DOMParser).parseFromString(aa,"text/xml").querySelector("xfdf > add")?new na.a(aa):new ma.a(aa):null};da.prototype.merge=
function(aa,y,w){var f=this;0===w&&(this.Pia(aa,y.Up),this.Ria(aa,y.DJ));var a=y.da[w];a&&(this.Sia(aa,a.Un),this.Uia(aa,a.u2,y.ex),this.Tia(aa,a.page,w),this.Qia(aa,a.uU));a=this.aa.Rb();if(w===a-1){var b=y.ex;Object.keys(b).forEach(function(e){b[e].lL||f.yY(aa,e,b[e])})}};da.prototype.Pia=function(aa,y){null!==y&&(aa=this.nw(aa),this.mr(aa,"calculation-order",y))};da.prototype.Ria=function(aa,y){null!==y&&(aa=this.nw(aa),this.mr(aa,"document-actions",y))};da.prototype.Sia=function(aa,y){var w=this,
f=this.mw(aa.querySelector("xfdf"),"annots");Object.keys(y).forEach(function(a){w.mr(f,'[name="'+a+'"]',y[a])})};da.prototype.Uia=function(aa,y,w){var f=this;if(0!==y.length){var a=this.nw(aa);y.forEach(function(b){var e=b.getAttribute("field"),h=w[e];h&&(f.yY(aa,e,h),f.mr(a,"null",b))})}};da.prototype.yY=function(aa,y,w){var f=this.nw(aa),a=f.querySelector('ffield[name="'+y+'"]');null!==w.ZC&&null===a&&this.mr(f,'ffield[name="'+y+'"]',w.ZC);aa=this.mw(aa.querySelector("xfdf"),"fields");y=y.split(".");
this.eN(aa,y,0,w.value);w.lL=!0};da.prototype.Tia=function(aa,y,w){null!==y&&(aa=this.nw(aa),aa=this.mw(aa,"pages"),this.mr(aa,'[number="'+(w+1)+'"]',y))};da.prototype.Qia=function(aa,y){Object.keys(y).forEach(function(w){(w=aa.querySelector('annots [name="'+w+'"]'))&&w.parentElement.removeChild(w)})};da.prototype.eN=function(aa,y,w,f){if(w===y.length)y=document.createElementNS("","value"),y.textContent=f,this.mr(aa,"value",y);else{var a=y[w];this.mw(aa,'[name="'+a+'"]',"field").setAttribute("name",
a);aa=aa.querySelectorAll('[name="'+a+'"]');1===aa.length?this.eN(aa[0],y,w+1,f):(a=this.rda(aa),this.eN(w===y.length-1?a:this.mqa(aa,a),y,w+1,f))}};da.prototype.rda=function(aa){for(var y=null,w=0;w<aa.length;w++){var f=aa[w];if(0===f.childElementCount||1===f.childElementCount&&"value"===f.children[0].tagName){y=f;break}}return y};da.prototype.mqa=function(aa,y){for(var w=0;w<aa.length;w++)if(aa[w]!==y)return aa[w];return null};da.prototype.mr=function(aa,y,w){y=aa.querySelector(y);null!==y&&aa.removeChild(y);
aa.appendChild(w)};da.prototype.nw=function(aa){var y=aa.querySelector("pdf-info");if(null!==y)return y;y=this.mw(aa.querySelector("xfdf"),"pdf-info");y.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");y.setAttribute("version","2");y.setAttribute("import-version","4");return y};da.prototype.mw=function(aa,y,w){var f=aa.querySelector(y);if(null!==f)return f;f=document.createElementNS("",w||y);aa.appendChild(f);return f};return da}();xa["default"]=Aa},484:function(Aa,xa){Aa=function(){function r(){}
r.prototype.DB=function(oa){var na={Up:null,DJ:null,ex:{},da:{}};oa=(new DOMParser).parseFromString(oa,"text/xml");na.Up=oa.querySelector("pdf-info calculation-order");na.DJ=oa.querySelector("pdf-info document-actions");na.ex=this.Oja(oa);na.da=this.$ja(oa);return na};r.prototype.Oja=function(oa){var na=oa.querySelector("fields");oa=oa.querySelectorAll("pdf-info > ffield");if(null===na&&null===oa)return{};var ma={};this.R7(ma,na);this.P7(ma,oa);return ma};r.prototype.R7=function(oa,na){if(null!==
na&&na.children){for(var ma=[],fa=0;fa<na.children.length;fa++){var da=na.children[fa];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(na=ma.shift(),fa=0;fa<na.element.children.length;fa++)da=na.element.children[fa],"value"===da.tagName?oa[na.name]={value:da.textContent,ZC:null,lL:!1}:da.children&&ma.push({name:na.name+"."+da.getAttribute("name"),element:da})}};r.prototype.P7=function(oa,na){na.forEach(function(ma){var fa=ma.getAttribute("name");oa[fa]?oa[fa].ZC=ma:oa[fa]=
{value:null,ZC:ma,lL:!1}})};r.prototype.$ja=function(oa){var na=this,ma={};oa.querySelectorAll("pdf-info widget").forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10)-1;na.eE(ma,da);ma[da].u2.push(fa)});oa.querySelectorAll("pdf-info page").forEach(function(fa){var da=parseInt(fa.getAttribute("number"),10)-1;na.eE(ma,da);ma[da].page=fa});this.eW(oa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10),aa=fa.getAttribute("name");na.eE(ma,da);ma[da].Un[aa]=fa});this.PV(oa).forEach(function(fa){var da=
parseInt(fa.getAttribute("page"),10);fa=fa.textContent;na.eE(ma,da);ma[da].uU[fa]=!0});return ma};r.prototype.eE=function(oa,na){oa[na]||(oa[na]={Un:{},uU:{},u2:[],page:null})};return r}();xa.a=Aa},496:function(Aa,xa,r){var oa=r(0),na=r(1);r.n(na);Aa=function(ma){function fa(da){var aa=ma.call(this)||this;aa.bda=Array.isArray(da)?da:[da];return aa}Object(oa.c)(fa,ma);fa.prototype.parse=function(){var da=this,aa={Up:null,DJ:null,ex:{},da:{}};this.bda.forEach(function(y){aa=Object(na.merge)(aa,da.DB(y))});
return aa};fa.prototype.eW=function(da){var aa=[];da.querySelectorAll("add > *").forEach(function(y){aa.push(y)});da.querySelectorAll("modify > *").forEach(function(y){aa.push(y)});return aa};fa.prototype.PV=function(da){return da.querySelectorAll("delete > *")};return fa}(r(484).a);xa.a=Aa},497:function(Aa,xa,r){var oa=r(0);Aa=function(na){function ma(fa){var da=na.call(this)||this;da.cda=fa;return da}Object(oa.c)(ma,na);ma.prototype.parse=function(){return this.DB(this.cda)};ma.prototype.eW=function(fa){return fa.querySelectorAll("annots > *")};
ma.prototype.PV=function(){return[]};return ma}(r(484).a);xa.a=Aa}}]);}).call(this || window)
