/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{456:function(Aa,xa,r){r.r(xa);r.d(xa,"ByteRangeRequest",function(){return z});var oa=r(0),na=r(1);r.n(na);var ma=r(2),fa=r(158);Aa=r(99);var da=r(262),aa=r(80),y=r(77),w=r(261),f=r(177);r=r(394);var a=[],b=[],e=window,h=function(){return function(){this.Ym=1}}(),n;(function(ba){ba[ba.UNSENT=0]="UNSENT";ba[ba.DONE=4]="DONE"})(n||(n={}));var z=function(){function ba(ia,ca,ea,ja){var ka=this;this.url=ia;this.range=ca;this.rf=ea;
this.withCredentials=ja;this.C5=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);e.Uint8Array&&(this.request.responseType="arraybuffer");ja&&(this.request.withCredentials=ja);x.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(ca.stop)?this.request.setRequestHeader("Range","bytes="+ca.start):this.request.setRequestHeader("Range",["bytes=",ca.start,"-",ca.stop-1].join("")));ea&&Object.keys(ea).forEach(function(ha){ka.request.setRequestHeader(ha,ea[ha])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=w.a.NOT_STARTED}ba.prototype.start=function(ia){var ca=this,ea=this.request;ea.onreadystatechange=function(){if(ca.aborted)return ca.status=w.a.ABORTED,ia({code:w.a.ABORTED});if(this.readyState===ca.C5.DONE){ca.DD();var ja=0===window.document.URL.indexOf("file:///");200===ea.status||206===ea.status||ja&&0===ea.status?(ja=e.rW(this),ca.IO(ja,ia)):(ca.status=
w.a.ERROR,ia({code:ca.status,status:ca.status}))}};this.request.send(null);this.status=w.a.STARTED};ba.prototype.IO=function(ia,ca){this.status=w.a.SUCCESS;if(ca)return ca(!1,ia)};ba.prototype.abort=function(){this.DD();this.aborted=!0;this.request.abort()};ba.prototype.DD=function(){var ia=Object(f.c)(this.url,this.range,b);-1!==ia&&b.splice(ia,1);if(0<a.length){ia=a.shift();var ca=new ba(ia.url,ia.range,this.rf,this.withCredentials);ia.request=ca;b.push(ia);ca.start(Object(f.d)(ia))}};ba.prototype.extend=
function(ia){var ca=Object.assign({},this,ia.prototype);ca.constructor=ia;return ca};return ba}(),x=function(ba){function ia(ca,ea,ja,ka,ha){ja=ba.call(this,ca,ja,ka)||this;ja.xj={};ja.dC=ea;ja.url=ca;ja.DISABLE_RANGE_HEADER=!1;ja.Yy=z;ja.DP=3;ja.rf=ha||{};return ja}Object(oa.c)(ia,ba);ia.prototype.Jw=function(ca,ea,ja){var ka=-1===ca.indexOf("?")?"?":"&";switch(ja){case !1:case y.a.NEVER_CACHE:ca=ca+ka+"_="+Object(na.uniqueId)();break;case !0:case y.a.CACHE:ca=ca+ka+"_="+ea.start+","+(Object(na.isUndefined)(ea.stop)?
"":ea.stop)}return ca};ia.prototype.dU=function(ca,ea,ja,ka){void 0===ja&&(ja={});return new this.Yy(ca,ea,ja,ka)};ia.prototype.Rca=function(ca,ea,ja,ka,ha){for(var la=0;la<a.length;la++)if(Object(na.isEqual)(a[la].range,ea)&&Object(na.isEqual)(a[la].url,ca))return a[la].fh.push(ka),a[la].NE++,null;for(la=0;la<b.length;la++)if(Object(na.isEqual)(b[la].range,ea)&&Object(na.isEqual)(b[la].url,ca))return b[la].fh.push(ka),b[la].NE++,null;ja={url:ca,range:ea,dC:ja,fh:[ka],NE:1};if(0===a.length&&b.length<
this.DP)return b.push(ja),ja.request=this.dU(ca,ea,ha,this.withCredentials),ja;a.push(ja);return null};ia.prototype.Ko=function(ca,ea,ja){var ka=this.Jw(ca,ea,this.dC);(ca=this.Rca(ka,ea,this.dC,ja,this.rf))&&ca.request.start(Object(f.d)(ca));return function(){var ha=Object(f.c)(ka,ea,b);if(-1!==ha){var la=--b[ha].NE;0===la&&b[ha].request&&b[ha].request.abort()}else ha=Object(f.c)(ka,ea,a),-1!==ha&&(la=--a[ha].NE,0===la&&a.splice(ha,1))}};ia.prototype.VV=function(){return{start:-fa.a}};ia.prototype.Dga=
function(){var ca=-(fa.a+fa.e);return{start:ca-fa.d,end:ca}};ia.prototype.hu=function(ca){var ea=this;this.jC=!0;var ja=fa.a;this.Ko(this.url,this.VV(),function(ka,ha,la){function pa(){var qa=ea.Ed.QV();ea.Ko(ea.url,qa,function(ra,ua){if(ra)return Object(ma.j)("Error loading central directory: "+ra),ca(ra);ua=Object(aa.a)(ua);if(ua.length!==qa.stop-qa.start)return ca("Invalid XOD file: Zip central directory data is wrong size! Should be "+(qa.stop-qa.start)+" but is "+ua.length);ea.Ed.VZ(ua);ea.bJ=
!0;ea.jC=!1;return ca(!1)})}if(ka)return Object(ma.j)("Error loading end header: "+ka),ca(ka,ha,la);ha=Object(aa.a)(ha);if(ha.length!==ja)return ca("Invalid XOD file: Zip end header data is wrong size!");try{ea.Ed=new da.a(ha)}catch(qa){return ca(qa)}ea.Ed.kia?ea.Ko(ea.url,ea.Dga(),function(qa,ra){if(qa)return Object(ma.j)("Error loading zip64 header: "+qa),ca(qa);ra=Object(aa.a)(ra);ea.Ed.Cia(ra);pa()}):pa()})};ia.prototype.oW=function(ca){ca(Object.keys(this.Ed.jo))};ia.prototype.hN=function(ca,
ea){var ja=this;if(this.Ed.ST(ca)){var ka=this.Ed.vx(ca);if(ka in this.xj){var ha=this.wh[ca];ha.Ls=this.xj[ka];ha.Ls.Ym++;ha.cancel=ha.Ls.cancel}else{var la=this.Ed.Mea(ca),pa=this.Ko(this.url,la,function(ra,ua){ra?(Object(ma.j)('Error loading part "'+ca+'": '+ra),ja.Ko(ja.url,la,function(va,Da){if(va)return ea(va,ca);ja.ZZ(Da,la,ka,ca,ea)})):ja.ZZ(ua,la,ka,ca,ea)}),qa=this.wh[ca];qa&&(qa.s1=!0,qa.cancel=function(){qa.Ls.Ym--;0===qa.Ls.Ym&&(pa(),delete ja.xj[ka])},this.xj[ka]=new h(ka),qa.Ls=this.xj[ka],
qa.Ls.cancel=qa.cancel)}}else delete this.wh[ca],ea(Error('File not found: "'+ca+'"'),ca)};ia.prototype.ZZ=function(ca,ea,ja,ka,ha){if(ca.length!==ea.stop-ea.start)ha(Error("Part data is wrong size!"),ka);else{do{if(!this.xj[ja])return;ka=this.xj[ja].Ym;for(var la=ea.nr.length,pa=0;pa<la;++pa){var qa=ea.nr[pa];ha(!1,qa.jr,ca["string"===typeof ca?"substring":"subarray"](qa.start,qa.stop),this.Ed.tX(qa.jr));qa.jr in this.wh&&delete this.wh[qa.jr]}}while(ka!==this.xj[ja].Ym);delete this.xj[ja]}};ia.DISABLE_RANGE_HEADER=
!1;ia.DP=3;return ia}(Aa.a);(function(ba){function ia(ca,ea,ja){var ka=ba.call(this)||this,ha;for(ha in ca)ka[ha]=ca[ha];ka.pua=ca;ka.startOffset=ea;ka.endOffset=ja;ka.dU=function(la,pa,qa,ra){Object(na.isUndefined)(pa.stop)?(pa.start+=ka.endOffset,pa.stop=ka.endOffset):(pa.start+=ka.startOffset,pa.stop+=ka.startOffset);la=ka.Jw(ka.url,pa,ka.dC);return new ca.Yy(la,pa,qa,ra)};return ka}Object(oa.c)(ia,ba);return ia})(x);Object(r.a)(x);Object(r.b)(x);xa["default"]=x}}]);}).call(this || window)
