/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{467:function(Aa,xa,r){function oa(){return!1}function na(x,ba,ia){if(!(ba in z))return!0;ba=z[ba];for(var ca=0;ca<ba.length;ca++){var ea=x;var ja=ba[ca];var ka=ia;if(ja.name in ea){var ha="",la=!1;ea=ea[ja.name];switch(ja.type){case "s":ha="String";la=Object(da.isString)(ea);break;case "a":ha="Array";la=Object(da.isArray)(ea);break;case "n":ha="Number";la=Object(da.isNumber)(ea)&&Object(da.isFinite)(ea);break;case "o":ha="Object",
la=Object(da.isObject)(ea)&&!Object(da.isArray)(ea)}la||ka.reject('Expected response field "'+ja.name+'" to have type '+ha);ja=la}else ka.reject('Response missing field "'+ja.name+'"'),ja=!1;if(!ja)return!1}return!0}function ma(x){for(var ba=0,ia=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];ba<ia.length;ba++){var ca=ia[ba],ea=ca;ca=ca.charAt(0).toUpperCase()+ca.slice(1);x[ea]&&(Object.defineProperty(x,ca,Object.getOwnPropertyDescriptor(x,
ea)),delete x[ea])}return x}r.r(xa);var fa=r(0),da=r(1);r.n(da);var aa=r(2);Aa=r(48);var y=r(23),w=r(487),f=r(99),a=r(394),b=r(43),e=r(177),h=function(){function x(){this.request=this.result=null;this.state=0;var ba=this;ba.promise=new Promise(function(ia,ca){ba.resolve=function(){if(0===ba.state||4===ba.state)ba.state=1,ba.result=arguments[0],ia.apply(null,arguments)};ba.reject=function(){if(0===ba.state||4===ba.state)ba.state=2,ca.apply(null,arguments)}})}x.prototype.au=function(){return 1===(this.state&
1)};x.prototype.Zha=function(){return 2===(this.state&2)};x.prototype.fj=function(){return!this.Zha()&&!this.au()};x.prototype.Aha=function(){return 4===(this.state&4)};x.prototype.XN=function(){this.state|=4};return x}(),n=function(){function x(){this.It={};this.Ob=[]}x.prototype.pop=function(){var ba=this.Ob.pop();this.It[ba.key]=void 0;return ba};x.prototype.push=function(ba,ia){ia={key:ba,data:ia};this.Ob.push(ia);this.It[ba]=ia.data};x.prototype.contains=function(ba){return!!this.It[ba]};x.prototype.get=
function(ba){return this.It[ba]};x.prototype.set=function(ba,ia){var ca=this;this.It[ba]=ia;this.Ob.forEach(function(ea,ja){ea.key===ba&&(ca.Ob[ja]=ea)})};x.prototype.remove=function(ba){var ia=this;this.It[ba]=void 0;this.Ob.forEach(function(ca,ea){ca.key===ba&&ia.Ob.splice(ea,1)})};x.prototype.length=function(){return this.Ob.length};return x}(),z={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},
{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};r=function(){function x(ba,ia,ca){var ea=this;this.CO=this.DU=!1;this.vh=this.DG=this.ov=this.Cf=this.pu=this.TI=this.qn=null;this.Rm=new h;
this.bq=new h;this.tC=!1;this.Mf=this.Le=this.Me=this.Bf=null;this.hg=[];this.eD=[];this.cache={};this.timeStamp=0;this.qh=[];this.pj=[];this.ZJ=null;this.qU=!1;this.i0=this.id=null;this.gM=this.ZW=oa;this.oi=0;this.iL=!1;this.IY=1;this.lj={};this.zs=0;this.Cu=new n;ia.endsWith("/")||(ia+="/");ca=ca||{};this.DU=ca.disableWebsockets||!1;this.CO=ca.singleServerMode||!1;null!=ca.customQueryParameters&&Object(b.b)("wvsQueryParameters",ca.customQueryParameters);ia.endsWith("blackbox/")||(ia+="blackbox/");
this.qn=ca.uploadData||null;this.ov=ca.uriData||null;this.TI=ca.cacheKey||null;if(this.pu=ca.officeOptions||null)this.pu=ma(this.pu);this.Cf=ca.rasterizerOptions||null;this.ef=ia;this.CJ=ba;this.Xo(!0);this.Ps=(new w.a(ia,null,this.$h())).Ida(!this.DU,function(ja){ea.qja(ja)},function(){return null},function(){ea.tC=!1},function(){ea.zma()})}x.prototype.kaa=function(){var ba=this;return new Promise(function(ia,ca){var ea=new XMLHttpRequest;ea.open("GET",ba.ef+"ck");ea.withCredentials=ba.$h();ea.onreadystatechange=
function(){ea.readyState===XMLHttpRequest.DONE&&(200===ea.status?ia():ca())};ea.send()})};x.prototype.poa=function(ba){this.ZW=ba||oa;this.gM=oa};x.prototype.U9=function(){this.L_();return this.Ps.qq(!0)};x.prototype.L_=function(){Object(fa.b)(this,void 0,void 0,function(){return Object(fa.d)(this,function(ba){switch(ba.label){case 0:return this.bq=new h,this.Rm=new h,this.tC=!1,this.id=null,this.qU=!1,[4,this.kaa()];case 1:return ba.ca(),[2]}})})};x.prototype.zma=function(){this.ZW();this.L_();this.Bf&&
(this.Bf.fj()?this.Bh(this.Bf.request):this.Bf.au()&&this.gM(this.Bf.result.url,"pdf")&&(this.Bf=null,this.K_()));this.Mf&&this.Mf.fj()&&this.Bh(this.Mf.request);this.Me&&this.Me.fj()?this.Bh(this.Me.request):this.Le&&this.Le.fj()&&this.MW();var ba;for(ba=0;ba<this.qh.length;ba++)this.qh[ba]&&(this.qh[ba].fj()?this.Bh(this.qh[ba].request):this.qh[ba].au()&&this.gM(this.qh[ba].result.url,"image")&&(this.qh[ba]=null,this.CF(Object(da.uniqueId)(),ba)));for(ba=0;ba<this.pj.length;ba++)this.pj[ba]&&this.pj[ba].fj()&&
!this.pj[ba].Aha()&&this.Bh(this.pj[ba].request);for(ba=0;ba<this.hg.length;ba++)this.hg[ba]&&this.hg[ba].fj()&&this.Bh(this.hg[ba].request)};x.prototype.hha=function(){return this.tC?Promise.resolve():(this.tC=!0,this.timeStamp=Date.now(),this.Ps.fE())};x.prototype.Qqa=function(){var ba=this,ia,ca,ea,ja,ka;return new Promise(function(ha,la){if(ba.qn)ia=new FormData,ia.append("file",ba.qn.fileHandle,ba.qn.fileHandle.name),ca=ba.qn.loadCallback,ja="upload",ea=ba.qn.extension;else if(ba.ov)ia={uri:ba.ov.uri,
Iua:ba.ov.shareId},ia=Object.keys(ia).map(function(ra){return ra+"="+(ia[ra]?encodeURIComponent(ia[ra]):"")}).join("&"),ka="application/x-www-form-urlencoded; charset=UTF-8",ca=ba.ov.loadCallback,ja="url",ea=ba.ov.extension;else{ha();return}var pa=new XMLHttpRequest,qa=Object(y.k)(ba.ef,"AuxUpload");qa=Object(e.a)(qa,{type:ja,ext:ea});pa.open("POST",qa);pa.withCredentials=ba.$h();ka&&pa.setRequestHeader("Content-Type",ka);pa.addEventListener("load",function(){if(pa.readyState===pa.DONE&&200===pa.status){var ra=
JSON.parse(pa.response);ba.CJ=ra.uri;ca(ra);ha(ra)}});pa.addEventListener("error",function(){la(pa.statusText+" "+JSON.stringify(pa))});ba.qn&&null!=ba.qn.onProgress&&(pa.upload.onprogress=function(ra){ba.qn.onProgress(ra)});pa.send(ia)})};x.prototype.qma=function(ba){this.password=ba||null;this.Rm.au()||(this.Rm=new h,this.Bh({t:"pages"}));return this.Rm.promise};x.prototype.ez=function(ba){this.ZJ=ba||null;this.Rm.au()||this.Bh({t:"pages"});return this.Rm.promise};x.prototype.Iw=function(ba){ba=
Object.assign(ba,{uri:encodeURIComponent(this.CJ)});this.ZJ&&(ba.ext=this.ZJ);this.vh&&(ba.c=this.vh);this.password&&(ba.pswd=this.password);this.TI&&(ba.cacheKey=this.TI);this.pu&&(ba.officeOptions=this.pu);this.Cf&&(ba.rastOptions=this.Cf);return ba};x.prototype.Yma=function(){0<this.Cu.length()&&10>=this.zs&&this.Zma(this.Cu.pop().data)};x.prototype.s9=function(ba){0<this.Cu.length()&&this.Cu.contains(ba)&&this.Cu.remove(ba)};x.prototype.Bh=function(ba){ba=this.Iw(ba);this.Ps.send(ba)};x.prototype.d0=
function(ba,ia){10<this.zs?this.Cu.push(ba,ia):(this.zs++,ba=this.Iw(ia),this.Ps.send(ba))};x.prototype.Zma=function(ba){this.zs++;ba=this.Iw(ba);this.Ps.send(ba)};x.prototype.Vl=function(ba){return ba};x.prototype.YW=function(ba){this.CO&&ba?Object(aa.j)("Server failed health check. Single server mode ignoring check."):!this.lta&&ba&&3>=this.oi?(this.iL=!0,this.Ps.qq()):3<this.oi&&(this.CO=!0)};x.prototype.qja=function(ba){var ia=this,ca=ba.data,ea=ba.err,ja=ba.t;switch(ja){case "upload":ea?this.Rqa.reject(ea):
this.Rqa.resolve("Success");break;case "pages":ea?this.Rm.reject(ea):na(ca,ja,this.Rm)&&this.Rm.resolve(ca);break;case "config":if(ea)this.bq.reject(ea);else if(na(ca,ja,this.bq)){this.YW(ca.unhealthy);ca.id&&(this.id=ca.id);if(ca.auth){var ka=Object(b.a)("wvsQueryParameters");ka.auth=ca.auth;Object(b.b)("wvsQueryParameters",ka)}ca.serverVersion&&(this.DG=ca.serverVersion,Object(aa.h)("[WebViewer Server] server version: "+this.DG));ca.serverID?(this.oi=ca.serverID===this.i0&&this.iL?this.oi+1:0,this.i0=
ca.serverID):this.oi=0;this.iL=!1;this.bq.resolve(ca)}break;case "health":ea?this.bq.reject(ea):na(ca,ja,this.bq)&&this.YW(ca.unhealthy);break;case "pdf":ca.url=Object(e.a)(this.ef+"../"+encodeURI(ca.url));ea?this.Bf.reject(ea):na(ca,ja,this.Bf)&&this.Bf.resolve(ca);break;case "ApString2Xod":ca.url=Object(e.a)(this.ef+"../data/"+encodeURI(ca.url));ea?this.lj[ca.rID].reject(ea):na(ca,ja,this.lj[ca.rID])&&this.lj[ca.rID].resolve(ca);break;case "docmod":ca.url=Object(e.a)(this.ef+"../"+encodeURI(ca.url));
ea?this.lj[ca.rID].reject(ea):na(ca,ja,this.Bf)&&this.lj[ca.rID].resolve(ca);break;case "xod":if(ea)this.Me&&this.Me.fj()&&this.Me.reject(ea),this.Le&&this.Le.fj()&&this.Le.reject(ea);else if(ca.notFound)ca.noCreate||this.Me&&this.Me.fj()&&this.Me.resolve(ca),this.Le&&this.Le.fj()&&this.Le.resolve(ca);else{ca.url&&(ca.url=Object(e.a)(this.ef+"../"+encodeURI(ca.url)));if(!this.Le||this.Le.au())this.Le=new h,this.Le.request={t:"xod",noCreate:!0};this.Me||(this.Me=new h,this.Me.request={t:"xod"});this.Le.resolve(ca);
this.Me.resolve(ca)}break;case "cAnnots":ka=this.Mf;if(ea)ka.reject(ea);else if(na(ca,ja,ka)){ka.XN();var ha=[],la=ca.annots;ca=function(Da){var sa=la[Da].s,Ca=la[Da].e,Ha=pa.ef+"../"+encodeURI(la[Da].xfdf),za="true"===la[Da].hasAppearance?Object(e.a)(Ha+".xodapp"):null,Ja=Object(da.range)(sa,Ca+1);ha[Da]={range:Ja,promise:new Promise(function(Oa,La){var Qa=new XMLHttpRequest;Qa.open("GET",Object(e.a)(Ha));Qa.responseType="text";Qa.withCredentials=ia.$h();Qa.addEventListener("load",function(){Qa.readyState===
Qa.DONE&&200===Qa.status&&Oa({Ir:Qa.response,Kl:za,range:Ja})});Qa.addEventListener("error",function(){La(Qa.statusText+" "+JSON.stringify(Qa))});Qa.send()})}};var pa=this;for(ea=0;ea<la.length;ea++)ca(ea);ka.resolve(ha)}break;case "annots":if(ea)this.Mf.reject(ea);else if(na(ca,ja,this.Mf)){this.Mf.XN();var qa=new XMLHttpRequest;ka=this.ef+"../"+encodeURI(ca.url);var ra=ca.hasAppearance?Object(e.a)(ka+".xodapp"):null;qa.open("GET",Object(e.a)(ka));qa.responseType="text";qa.withCredentials=this.$h();
qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ia.Mf.resolve({Ir:qa.response,Kl:ra})});qa.addEventListener("error",function(){ia.Mf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.zs--;var ua=this.qh[ca.p];ea?ua.promise.reject(ea):na(ca,ja,ua)&&(ua.result=ca,ua.result.url=Object(e.a)(this.ef+"../"+encodeURI(ua.result.url)),ua.resolve(ua.result));break;case "tiles":this.zs--;ua=ca.rID;ka=this.hg[ua];this.hg[ua]=null;this.eD.push(ua);
if(ea)ka.reject(ea);else if(na(ca,ja,ka)){for(ea=0;ea<ca.tiles.length;ea++)ca.tiles[ea]=Object(e.a)(this.ef+"../"+encodeURI(ca.tiles[ea]));ka.resolve(ca)}break;case "text":ua=this.pj[ca.p];if(ea)ua.reject(ea);else if(na(ca,ja,ua)){ua.XN();var va=new XMLHttpRequest;ca=Object(e.a)(this.ef+"../"+encodeURI(ca.url));va.open("GET",ca);va.withCredentials=this.$h();va.addEventListener("load",function(){va.readyState===va.DONE&&200===va.status&&(ua.result=JSON.parse(va.response),ua.resolve(ua.result))});va.addEventListener("error",
function(Da){ua.reject(va.statusText+" "+JSON.stringify(Da))});va.send()}break;case "progress":"loading"===ca.t&&this.trigger(f.a.Events.DOCUMENT_LOADING_PROGRESS,[ca.bytes,ca.total])}this.Yma();!ja&&ba.echo&&ba&&"apstring2xod"===ba.echo.t&&(ba=ba.echo.reqID)&&(2<=parseInt(this.DG,10)?this.lj[ba].reject("Message unhandled by server"):this.lj[ba].reject())};x.prototype.nea=function(){return Object(fa.b)(this,void 0,void 0,function(){return Object(fa.d)(this,function(ba){switch(ba.label){case 0:return[4,
this.hha()];case 1:return ba.ca(),[2,this.bq.promise]}})})};x.prototype.Uda=function(ba){for(var ia=this,ca=new XMLHttpRequest,ea=Object(e.a)(this.ef+"aul",{id:this.id}),ja=new FormData,ka={},ha=0;ha<ba.body.length;ha++){var la=ba.body[ha];ka[la.id]=la.EI.w+";"+la.EI.h;ja.append(la.id,la.EI.dataString)}ba={t:"apstring2xod",reqID:this.IY++,parts:ka};var pa=this.Iw(ba);ja.append("msg",JSON.stringify(pa));this.lj[pa.reqID]=new h;ca.open("POST",ea);ca.withCredentials=this.$h;ea=new Promise(function(qa,
ra){ca.onreadystatechange=function(){4===ca.readyState&&(200===ca.status?qa():ra("An error occurred while sending down appearance strings to the server"))}});ca.send(ja);return ea.then(function(){return ia.lj[pa.reqID].promise})};x.prototype.W9=function(){var ba=this.DG.split("-")[0].split("."),ia=["1","5","9"];if(3!==ba.length)throw Error("Invalid WVS version length.");if(3!==ia.length)throw Error("Invalid version length.");for(var ca=0;ca<ba.length;++ca){if(ia.length===ca||ba[ca]>ia[ca])return-1;
if(ba[ca]!==ia[ca])return 1}return 0};x.prototype.Yp=function(){return 0>=this.W9()};x.prototype.hK=function(){this.Mf||(this.Mf=new h,this.Yp()?this.Mf.request={t:"cAnnots"}:this.Mf.request={t:"annots"},this.Bh(this.Mf.request));return this.Mf.promise};x.prototype.CF=function(ba,ia){this.qh[ia]||(this.qh[ia]=new h,this.qh[ia].request={t:"image",p:ia},this.d0(ba,this.qh[ia].request));return this.qh[ia].promise};x.prototype.rma=function(ba){this.pj[ba]||(this.pj[ba]=new h,this.pj[ba].request={t:"text",
p:ba},this.Bh(this.pj[ba].request));return this.pj[ba].promise};x.prototype.sma=function(ba,ia,ca,ea,ja){var ka=this.hg.length;this.eD.length&&(ka=this.eD.pop());this.hg[ka]=new h;this.hg[ka].request={t:"tiles",p:ia,z:ca,r:ea,size:ja,rID:ka};this.d0(ba,this.hg[ka].request);return this.hg[ka].promise};x.prototype.K_=function(){this.Bf||(this.Bf=new h,this.Bf.request={t:"pdf"},this.qU?this.Bf.resolve({url:this.CJ}):this.Bh(this.Bf.request));return this.Bf.promise};x.prototype.gW=function(ba){var ia=
this,ca=new XMLHttpRequest,ea=Object(e.a)(this.ef+"aul",{id:this.id}),ja=new FormData,ka={};ba.annots&&(ka.annots="xfdf");ba.watermark&&(ka.watermark="png");ba.redactions&&(ka.redactions="redact");ka={t:"docmod",reqID:this.IY++,parts:ka};ba.print&&(ka.print=!0);var ha=this.Iw(ka);ja.append("msg",JSON.stringify(ha));return Promise.all([ba.annots,ba.watermark,ba.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var pa=la[0],qa=la[1];la=la[2];pa&&ja.append("annots",pa);qa&&
ja.append("watermark",qa);la&&ja.append("redactions",la);ia.lj[ha.reqID]=new h;ca.open("POST",ea);ca.withCredentials=ia.$h;pa=new Promise(function(ra,ua){ca.onreadystatechange=function(){4===ca.readyState&&(200===ca.status?ra():ua("An error occurred while sending down annotation data to the server"))}});ca.send(ja);return pa.then(function(){return ia.lj[ha.reqID].promise})})};x.prototype.MW=function(){this.Le||(this.Le=new h,this.Le.request={t:"xod",noCreate:!0},this.Bh(this.Le.request));return this.Le.promise};
x.prototype.tma=function(){this.Me||(this.Me=new h,this.Me.request={t:"xod"},this.Bh(this.Me.request));return this.Me.promise};x.prototype.So=function(){return!0};x.prototype.request=function(){};x.prototype.d_=function(){};x.prototype.abort=function(){for(var ba=0;ba<this.hg.length;ba++)this.hg[ba]&&(this.hg[ba].resolve(null),this.hg[ba]=null,this.eD.push(ba));this.close()};x.prototype.PF=function(ba){this.vh=this.vh||{};this.vh.headers=ba};x.prototype.Xo=function(ba){this.vh=this.vh||{};this.vh.internal=
this.vh.internal||{};this.vh.internal.withCredentials=ba};x.prototype.$h=function(){return this.vh&&this.vh.internal?this.vh.internal.withCredentials:null};x.prototype.getFileData=function(){return Promise.reject()};return x}();Object(Aa.a)(r);Object(a.a)(r);Object(a.b)(r);xa["default"]=r},487:function(Aa,xa,r){var oa=r(0),na=r(2),ma=r(23),fa=r(43),da=r(177),aa=r(79),y=function(){function f(a,b,e,h,n,z){void 0===e&&(e=null);void 0===h&&(h=null);void 0===n&&(n=null);void 0===z&&(z=null);this.rY=!1;
this.oi=0;this.hT=this.mra(a);this.url=b?this.hT+"/"+b:this.hT+"/ws";this.tJ=e;this.Fy=h;this.Gw=n;this.yN=z}f.prototype.mra=function(a){var b=a.indexOf("://"),e="ws://";0>b?b=0:(5===b&&(e="wss://"),b+=3);var h=a.lastIndexOf("/");0>h&&(h=a.length);return e+a.slice(b,h)};f.prototype.send=function(a){this.kp.readyState===WebSocket.CLOSED||this.rY||this.kp.send(JSON.stringify(a))};f.prototype.fE=function(){return Object(oa.b)(this,void 0,void 0,function(){var a,b=this;return Object(oa.d)(this,function(){a=
Object(fa.a)("wvsQueryParameters");a.bcid=Object(ma.l)(8);Object(fa.b)("wvsQueryParameters",a);return[2,new Promise(function(e,h){var n=Object(da.a)(b.url);b.kp=new WebSocket(n);b.kp.onopen=function(){b.Fy&&b.Fy();e()};b.kp.onerror=function(z){b.rY=!0;h(z)};b.kp.onclose=function(z){var x=z.code;return Object(oa.b)(b,void 0,void 0,function(){var ba=this;return Object(oa.d)(this,function(ia){switch(ia.label){case 0:return this.Gw&&this.Gw(),3E3===x?[3,3]:8>this.oi++?[4,new Promise(function(ca){return setTimeout(function(){return Object(oa.b)(ba,
void 0,void 0,function(){return Object(oa.d)(this,function(ea){switch(ea.label){case 0:return this.yN(),[4,this.fE()];case 1:return ea.ca(),ca(),[2]}})})},3E3)})]:[3,2];case 1:return ia.ca(),[3,3];case 2:h(aa.a),ia.label=3;case 3:return[2]}})})};b.kp.onmessage=function(z){z&&z.data&&(z=JSON.parse(z.data),z.hb?b.send({hb:!0}):z.end?close():b.tJ(z))}})]})})};f.prototype.qq=function(a){void 0===a&&(a=!1);this.oi=0;a?this.kp.close(3E3):this.kp.close();return Promise.resolve()};return f}(),w=function(){function f(a,
b,e,h,n,z,x){void 0===h&&(h=null);void 0===n&&(n=null);void 0===z&&(z=null);void 0===x&&(x=null);this.oi=this.BF=this.id=0;this.Sx=!1;this.request=null;a=this.Lka(a);this.url=b?a+"/"+b+"pf":a+"/pf";this.wG=e;this.tJ=h;this.Fy=n;this.Gw=z;this.yN=x}f.prototype.Lka=function(a){var b=a.lastIndexOf("/");0>b&&(b=a.length);return a.slice(0,b)};f.prototype.V$=function(a){a=a.split("\n");for(a[a.length-1]&&a.pop();0<a.length&&3>a[a.length-1].length;)"]"===a.pop()&&(this.id=0);0<a.length&&3>a[0].length&&a.shift();
for(var b=0;b<a.length;++b)a[b].endsWith(",")&&(a[b]=a[b].substr(0,a[b].length-1));return a};f.prototype.T_=function(){return Object(oa.b)(this,void 0,void 0,function(){var a=this;return Object(oa.d)(this,function(b){switch(b.label){case 0:return 8>this.oi++?[4,new Promise(function(e){return setTimeout(function(){a.yN();a.fE();e()},3E3)})]:[3,2];case 1:b.ca(),b.label=2;case 2:return[2]}})})};f.prototype.Nka=function(a){Object(oa.b)(this,void 0,void 0,function(){var b,e;return Object(oa.d)(this,function(h){switch(h.label){case 0:b=
null,e=0,h.label=1;case 1:if(!(e<a.length))return[3,6];b=JSON.parse(a[e]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(na.j)("Reconnecting, new server detected");this.qq();return[4,this.T_()];case 3:return h.ca(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Sx||this.tJ(b),h.label=5;case 5:return++e,[3,1];case 6:return[2]}})})};f.prototype.nja=function(a){Object(oa.b)(this,void 0,void 0,function(){var b,
e,h;return Object(oa.d)(this,function(n){switch(n.label){case 0:if(!(3<=a.readyState))return[3,2];try{b=a.responseText.length}catch(z){return Object(na.h)("caught exception"),[2]}if(0<b)try{e=this.V$(a.responseText),0===this.id&&0<e.length&&(h=JSON.parse(e.shift()),this.id=h.id,this.oi=0),this.Nka(e)}catch(z){}return this.Sx?[3,2]:[4,this.gV()];case 1:n.ca(),n.label=2;case 2:return[2]}})})};f.prototype.gV=function(){return Object(oa.b)(this,void 0,void 0,function(){var a=this;return Object(oa.d)(this,
function(){return[2,new Promise(function(b,e){function h(){return Object(oa.b)(a,void 0,void 0,function(){return Object(oa.d)(this,function(z){switch(z.label){case 0:e(),this.qq(),z.label=1;case 1:return this.Sx&&8>this.oi?[4,this.T_()]:[3,3];case 2:return z.ca(),[3,1];case 3:return[2]}})})}a.request=new XMLHttpRequest;a.request.withCredentials=a.wG;var n=Object(da.a)(a.url,0!==a.id?{id:String(a.id),uc:String(a.BF)}:{uc:String(a.BF)});a.BF++;a.request.open("GET",n,!0);a.request.setRequestHeader("Cache-Control",
"no-cache");a.request.setRequestHeader("X-Requested-With","XMLHttpRequest");a.request.onreadystatechange=function(){a.nja(a.request)};a.request.addEventListener("error",h);a.request.addEventListener("timeout",h);a.request.addEventListener("load",function(){a.Fy&&a.Fy();b()});a.request.send()})]})})};f.prototype.fE=function(){var a=Object(fa.a)("wvsQueryParameters");a.bcid=Object(ma.l)(8);Object(fa.b)("wvsQueryParameters",a);this.BF=this.id=0;this.Sx=!1;return this.gV()};f.prototype.send=function(a){var b=
this,e=new XMLHttpRequest;e.withCredentials=this.wG;var h=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(a));e.addEventListener("error",function(){b.qq()});e.open("POST",h);e.setRequestHeader("X-Requested-With","XMLHttpRequest");e.send(n)};f.prototype.qq=function(){this.id=0;this.Sx=!0;this.Gw&&this.Gw();this.request.abort();return Promise.resolve()};return f}();Aa=function(){function f(a,b,e){this.OT=a;this.target=b;this.wG=e}f.prototype.Ida=function(a,
b,e,h,n){void 0===a&&(a=!0);void 0===b&&(b=null);void 0===e&&(e=null);void 0===h&&(h=null);void 0===n&&(n=null);return a?new y(this.OT,this.target,b,e,h,n):new w(this.OT,this.target,this.wG,b,e,h,n)};return f}();xa.a=Aa}}]);}).call(this || window)
